### ISSUE TITLE
Fixing warnings

### ISSUE THREAD

**Issue by arielpontes** [tfranzel/drf-spectacular#456] opened 2021-07-13 14:55 UTC
I'm getting the following warning when I generate the Swagger UI:

    Warning #0: NameserverViewSet: could not derive type of path parameter "domain_pk" because model "<class 
    'myproject.myapp.models.nameserver.Nameserver'>" did contain no such field. Consider annotating parameter with 
    @extend_schema. Defaulting to "string".

It's not clear to me how exactly I'm supposed to use `@extend_schema` to fix this problem. This is a nested endpoint and I'm using `drf-nested-routers`. The endpoint looks like this:

    /domain/{domain_pk}/nameservers/

And in my `get_queryset` I have:

    def get_queryset(self):
        return Nameserver.objects.filter(domain=self.kwargs.get("domain_pk"))

It seems `drf-spectacular` and `drf-nested-routers` don't play very well together. Is there any easy workaround for this situation?

**Comment by tfranzel** [comment] 2021-07-13 15:04
which spectacular version are you using?

**Comment by arielpontes** [comment] 2021-07-13 16:07
drf-spectacular==0.17.2

**Comment by tfranzel** [comment] 2021-07-13 16:31
weird because i thought we fixed this with #251. this is probably a duplicate of #453

this is actually supposed to work.  can you provide a minimal reproduction snippet so i can debug the issue?

**Comment by arielpontes** [comment] 2021-07-14 08:40
Sure. Actually in the process of writing this snippet I think I managed to narrow down the problem a bit.

# Models
```
class Parent(models.Model):
    pass


class Child(models.Model):
    parent = models.ForeignKey(Parent, on_delete=CASCADE)
```

# Serializers

```
class ParentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Parent
        fields = "__all__"


class ChildSerializer(serializers.ModelSerializer):
    class Meta:
        model = Child
        fields = "__all__"
```

# Views

```
class ParentViewSet(viewsets.ModelViewSet):
    lookup_value_regex = "[0-9]+"  # <--- I think this is the problem

    queryset = Parent.objects.all()
    serializer_class = ParentSerializer


class ChildViewSet(viewsets.ModelViewSet):

    serializer_class = ChildSerializer

    def get_queryset(self):
        return Parent.objects.filter(id=self.kwargs.get("parent_pk"))
```

# Solutions
I managed to find two solutions that fixed my problem:

1. Remove the line with `lookup_value_regex = "[0-9]+"`.
2. Add a line with `lookup_field = "id"` right above it.

**Comment by tfranzel** [comment] 2021-09-13 12:10
hi @arielpontes, finally got around working on this issue. could you try out #511? it contains several small fixes that revolve around this problem. also added tests for `drf-nested-routers`

**Comment by tfranzel** [comment] 2021-09-21 16:21
this has been severely improved in ba2f799 (and prior commits). path variable detection should now work as expected without using `lookup_field = 'id'` or other patches.

related but independent from that, a new setting `SCHEMA_COERCE_PATH_PK_SUFFIX` was added to globally coerce `_pk` names for convenience.

**Comment by tfranzel** [comment] 2021-10-03 17:54
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-10-03 17:54 UTC
Labels: enhancement, fix confirmation pending

**Comment by mglowinski93** [comment] 2021-11-29 07:03
Hi,
I've similar issue with version `0.21.0`.

Warning, which i get:
```
Warning #0: MachinePlcsViewSet: could not derive type of path parameter "line_pk" because model "plcs_crud.models.Plc" contained no such field. Consider annotating parameter with @extend_schema. Defaulting to "string".
```

**Views:**
```python
@extend_schema_view(
    list=extend_schema(description="Returns a list of all existing PLC controllers."),
    create=extend_schema(description="Creates single PLC controller."),
    retrieve=extend_schema(
        description="Retrieves the details of an existing PLC controller."
    ),
    update=extend_schema(description="Replaces the existing PLC controller resource."),
    partial_update=extend_schema(
        description="Updates part of the existing PLC controller data."
    ),
    destroy=extend_schema(description="Delete an existing PLC controller."),
)
class PlcViewSet(viewsets.ModelViewSet):
    queryset = models.Plc.objects.all()

    def get_serializer_class(self):
        return serializers.PlcSerializer


@extend_schema_view(
    list=extend_schema(
        description="Returns a list of all existing PLC controllers assigned to specific machine."
    ),
    retrieve=extend_schema(
        description="Retrieves the details of an existing PLC controller "
        "assigned to specific machine."
    ),
)
class MachinePlcsViewSet(PlcViewSet):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return models.Plc.objects.filter(machine_id=self.kwargs["machine_pk"])
```

**Serializer:**
```python
class PlcSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Plc
        fields = "__all__"
```

**Routers:**
```python
# Router responsible for handling URL /api/lines/<LINE_ID>/machines/<MACHINE_ID>/plcs.
lines_machines_router = routers.NestedSimpleRouter(
    parent_router=lines_router, parent_prefix="machines", lookup="machine"
)
lines_machines_router.register(
    prefix="plcs",
    viewset=plcs_api_views.MachinePlcsViewSet,
    basename="line-machine-plcs",
)





# Router responsible for handling URL /api/machines/<MACHINE_ID>/plcs.
machines_router = routers.NestedSimpleRouter(
    parent_router=router, parent_prefix="machines", lookup="machine"
)
machines_router.register(
    prefix="plcs",
    viewset=plcs_api_views.MachinePlcsViewSet,
    basename="machine-plcs",
)
```


Any tip how to solve that issue:)?
