### ISSUE TITLE
drf_spectacular.contrib.django_filters.DjangoFilterBackend not accepting inner object filters

### ISSUE THREAD

**Issue by jtsay362** [tfranzel/drf-spectacular#155] opened 2020-09-23 05:18 UTC
**Describe the bug**

I am using Django filters and drf-spectacular together so I tried using drf_spectacular.contrib.django_filters.DjangoFilterBackend instead of django_filters.rest_framework.DjangoFilterBackend. However, it causes errors during schema generation, possibly due to filters on inner objects.

**To Reproduce**
I'm using django 2.2, drf-spectacular 0.9.13, and django-filter 2.3.0. 

Replace django_filters.rest_framework.DjangoFilterBackend with drf_spectacular.contrib.django_filters.DjangoFilterBackend in REST_FRAMEWORK.DEFAULT_FILTER_BACKENDS in settings.py.

I have models like this:
```
class A(models.Model):
  uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

class B(models.Model):
  uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
  a = models.ForeignKey(A, on_delete=models.CASCADE)

class BFilter(filters.FilterSet):
    a__uuid = CharFilter()

    class Meta:
        model = B
        fields = ['a__uuid']
```

If I start the server locally and navigate to the standard API Doc views, I get 

django.core.exceptions.FieldDoesNotExist: B has no field named 'a__uuid'

**Expected behavior**

No error should occur, it would be nice if drf_spectacular could figure out this is a reference to another model.

**Comment by tfranzel** [comment] 2020-09-23 07:49
hey @jtsay362. although i'm not too familiar with django-filters, i suspect this does not work.

if if didn't miss something, your example is not recognized by django-filters. i slightly adapted https://github.com/tfranzel/drf-spectacular/blob/master/tests/contrib/test_django_filters.py with your example.

isn't it supposed to be the following? since this is a forward (foreign key) relation you do not have the `a` in `b`. that would only be the case for a reverse relation. 

```
class BFilter(filters.FilterSet):
    process_type__uuid = CharFilter()

    class Meta:
        model = B
        fields = ['process_type__uuid']
```

**Comment by jtsay362** [comment] 2020-09-29 17:06
I'm sorry, I was trying to simplify my usage to paste here, but I forgot to change "process_type" to "a". I edited my original comment. Before simplification, the filter does work. Would the edited version be supported by drf_spectacular?

**Comment by tfranzel** [comment] 2020-09-29 22:07
i just realized that you are using `0.9.13`. master contains fixes for `drf-filter` (#153) which are not in a release yet. on master i would say it works as expected. i edited

https://github.com/tfranzel/drf-spectacular/blob/master/tests/contrib/test_django_filters.py

to translate your usecase to our test by adding:

```python
class ProductFilter(FilterSet):
    ....
    subproduct__sub_price = NumberFilter()
```

which works as expected as far as i can tell.  can you confirm that the issue persists on the current master?

**Comment by tfranzel** [comment] 2020-10-05 15:52
@jtsay362 `0.9.14` does contain those fixes now. can you confirm the issue is gone?

**Comment by jtsay362** [comment] 2020-10-06 07:51
Hi, sorry I was not able to test it before it was released. Unfortunately with 0.9.14, I still get the same error like:
"django.core.exceptions.FieldDoesNotExist: B has no field named 'a__uuid'. I will confirm this isn't an issue with my Docker setup, but just want to give you this data point for now.

**Comment by tfranzel** [comment] 2020-10-06 08:58
Hey @jtsay362, unfortunately i was not able to reproduce your problem. i extended the test with your use case. Your `A` is `OtherSubProduct` here. as far as i can tell this is exactly your example. could you modify the test so that it breaks? not sure what else i can do to help you out here.

the related model:
https://github.com/tfranzel/drf-spectacular/blob/d988a9c30b2362a721b55bab400f55dd887fb5df/tests/contrib/test_django_filters.py#L25-L26

the foreign key:
https://github.com/tfranzel/drf-spectacular/blob/d988a9c30b2362a721b55bab400f55dd887fb5df/tests/contrib/test_django_filters.py#L29-L33

the filter definition
https://github.com/tfranzel/drf-spectacular/blob/d988a9c30b2362a721b55bab400f55dd887fb5df/tests/contrib/test_django_filters.py#L54

which works as expected and produces 

https://github.com/tfranzel/drf-spectacular/blob/d988a9c30b2362a721b55bab400f55dd887fb5df/tests/contrib/test_django_filters.yml#L36-L41

**Comment by jtsay362** [comment] 2020-10-08 06:37
Thanks for looking into it further. Actually it does work without exception if I just output to a file. The exceptions only happen when I use the spec redoc view or the swagger UI views (SpectacularSwaggerView,
  SpectacularRedocView), or the schema view (SpectacularAPIView), and point my browser to the endpoints exposed by those. This is good enough for me since I don't plan on serving API documentation from django, but maybe something you want to look into. Thanks again for all your hard work on this project!

**Comment by tfranzel** [comment] 2020-10-10 11:51
sure, no problem. thanks for the kind words. if your code works in the CLI and not the View, it does indicate that there is something different in your request object that may lead to this. though, retrieving this test schema through `SpectacularAPIView` did work in the tests. not sure what else i can do here.

if you like to get to the bottom of this, i would need more information. if you are satisfied with this outcome please close the issue, as i cannot go further without a reproduction example.

**Closed** 2020-10-10 16:38 UTC

**Comment by jtsay362** [comment] 2020-10-10 16:39
I'm closing this because it works for my needs. In the meantime I will try to see why serving the api schema in my setup raises the exception.

**Comment by Debutantepull-request** [comment] 2025-01-31 17:06
@jtsay362 https://pythoner.space/questions/unique-django-exception-invalid-uuid
