### ISSUE TITLE
[Q] Unversioned endpoints appearing below versioned endpoint

### ISSUE THREAD

**Issue by ronaldho** [tfranzel/drf-spectacular#926] opened 2023-01-31 03:51 UTC
I've addressed most of the egregious errors after importing drf-spectacular to my project. I've tried looking extensively in all the github issues (#253, #22, #367, #420) to see if I can find a solution, but I've come up empty thus far...

Potentially releveant info:

- We use a custom regex that looks like this:
  ` url(r'^api/(?P<version>(v?\d\.\d+))/', include("braintest.api.urls", namespace="apiv")),`
- We also have a corresponding middleware that overrides `URLPathVersioning` to handle the incoming versioning in the URL. We need it as a bunch of serializers depend on a float to check versioning
  eg:
  
  ```
  class CustomVersioning(URLPathVersioning):
    def determine_version(self, request, *args, **kwargs):
        version = super(CustomVersioning, self).determine_version(request, *args, **kwargs) or "1.0"
        version = float(version)
        return version
  ```
  

After these two changes above, when I hit my Swagger UI at `localhost/api/schema/swagger-ui/?version=1.6/` it groups all the endpoints under 1.6, and then below that, all the endpoints in their respective classes, but without versioning. I attached a screenshot below to illustrate the issue.

![1 6 section](https://user-images.githubusercontent.com/2703939/215658544-10b1561b-eb56-4ba2-a8c7-98a1faa9c634.png)
![unversioned](https://user-images.githubusercontent.com/2703939/215658552-7c8c9f6d-df8a-427b-a5b2-4bfd570c77e0.png)

Is this expected behaviour? I feel like all the versioned endpoints shouldn't duplicate themselves again without their versions though. Thank you in advance!

**Comment by tfranzel** [comment] 2023-01-31 09:54
> Potentially releveant info:

shouldn't be an issue given that this is all based on a supported versioning class (URLPathVersioning)

> Is this expected behaviour? I feel like all the versioned endpoints shouldn't duplicate themselves again without their versions though.

I think not. There shouldn't be duplication unless you add `include("braintest.api.urls",...)` twice into the `urlpatterns`. this is the expected behavior:

no version given: unversioned endpoints
explicit version like you did or `DEFAULT_VERSION`:  unversioned endpoints + versioned endpoints (for that version)

All the endpoints are iterated ONCE, so they should fall in one category and thats it. no duplication. at least that is the intended funtionality.

FYI: you should set `SCHEMA_PATH_PREFIX` so your tag/operation_id naming is nicer. This is not really fixing your problem, but definitely a cosmetic improvement.

https://github.com/tfranzel/drf-spectacular/blob/24b8a9890d59900d102490a48e286d08cdcc7ab5/drf_spectacular/settings.py#L8-L13

**Comment by tfranzel** [comment] 2023-02-07 20:23
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2023-02-07 20:23 UTC
