### ISSUE TITLE
Openapiexample not working

### ISSUE THREAD

**Issue by sudalking777** [tfranzel/drf-spectacular#831] opened 2022-10-09 08:58 UTC
```
# settings.py
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
}
```

```
# view
class CreateTokenPairView(TokenViewBase):

    serializer_class = serializers.CustomObtainPairSerializer

    @extend_schema(
        responses={
            200: serializers.TokenObtainPairSerializer,
            401: OpenApiResponse(description="sample description"),
        },
    )
    def post(self, request, *args, **kwargs):

        serializer = self.get_serializer(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        except ValidationError:
            raise AuthenticationFailed(
                detail="No active account found with the given credentials"
            )

        return Response(serializer.validated_data, status=status.HTTP_200_OK)
```

```
# serializer
@extend_schema_serializer(
    examples=[
        OpenApiExample(
            name="sampel name1",
            description="sample description",
            value={
                "refresh_token": "sample_refresh_token",
                "access_token": "sample_access_token",
                "user": {
                    "name": "sample name",
                    "nickname": "sample nickname",
                    "gender": "m",
                    "phone_number": "01012341234",
                    "birth_date": "2000-01-01",
                    "email": "test@example.com",
                    "profile_photo": "full path",
                    "is_agree_marketing_email": True,
                    "is_agree_marketing_sms": False,
                    "refund_account_number": "110-110-111110",
                    "refund_bank": "ha",
                },
            },
            response_only=True,
            status_codes=[200],
        ),
        OpenApiExample(
            name="sample name2",
            description="sample description",
            value={"google_id": "123456"},
            response_only=True,
            status_codes=[200],
        ),
    ],
)
class TokenObtainPairSerializer(CustomMixin, CustomObtainSerializer):

   .............

```

response
code: 200
Description: No response body
OpenApiExample is not working

but when i set this
```
# settings.py
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": False,
}
```
OpenApiExample is working

**Comment by tfranzel** [comment] 2022-10-09 09:16
please provide more context. I cannot reproduce your statement.

**Comment by sudalking777** [comment] 2022-10-09 10:46
I just revised the text

**Comment by tfranzel** [comment] 2022-11-25 11:14
Examples only make sense when the endpoint does have a schema. So when a endpoint response is detected as `no content` and all your examples are marked as `response_only`, there is nothing to show really.

It looks like your `TokenObtainPairSerializer` only has `writeOnly` fields and not fields on your response. 

turning off `COMPONENT_SPLIT_REQUEST` just removed the distinction between request/response.

**Closed** 2023-02-27 23:05 UTC
