### ISSUE TITLE
Filters are not rendering in swagger-ui

### ISSUE THREAD

**Issue by Javedgouri** [tfranzel/drf-spectacular#177] opened 2020-10-24 07:52 UTC
class UserViewSet(mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.UpdateModelMixin, viewsets.GenericViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [django_rest_filter.DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]

    search_fields = ['first_name', 'last_name', 'username']
    ordering_fields = ['created', 'first_name', 'last_name']
    filterset_fields = ['user_type', 'email', 'phone_number']

this is my viewSet but it is not rendering in my ui.
![Screenshot 2020-10-24 at 1 19 40 PM](https://user-images.githubusercontent.com/14862494/97071168-02550400-15fc-11eb-9b7d-64c5cb1120e1.png)

**Comment by KimSoungRyoul** [comment] 2020-10-24 10:41
unfortunatly I can't reproduce your issue.

can you more detail your project environment?  
like a django drf Version, & spectacular Version or SourceCdoe detail 

~~~Python
from django.contrib.auth.models import User
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters as drf_filters

from rest_framework import mixins, serializers
from rest_framework import viewsets


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = "__all__"


class UserViewSet(
    mixins.RetrieveModelMixin,
    mixins.ListModelMixin,
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [
        DjangoFilterBackend,
        drf_filters.SearchFilter,
        drf_filters.OrderingFilter,
    ]
    filterset_fields = ["email", "username"]
    search_fields = ["first_name", "last_name", "username"]

~~~


<img width="1062" alt="스크린샷 2020-10-24 오후 7 38 18" src="https://user-images.githubusercontent.com/24240623/97079615-7e693f00-1630-11eb-8d47-e7375297c799.png">

**Comment by Javedgouri** [comment] 2020-10-24 20:20
source code - 
drf version - djangorestframework==3.12.1
django version - Django==3.1.2

drf-spectacular - drf-spectacular==0.10.0




from django_filters import rest_framework as django_rest_filter
from rest_framework import (permissions, viewsets, filters, status, generics, views, mixins, exceptions, )


class UserViewSet(mixins.RetrieveModelMixin, mixins.ListModelMixin, mixins.UpdateModelMixin, viewsets.GenericViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [django_rest_filter.DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]

    search_fields = ['first_name', 'last_name', 'username']
    ordering_fields = ['created', 'first_name', 'last_name']
    filterset_fields = ['user_type', 'email', 'phone_number']

    def get_queryset(self):
        queryset = self.__filter_queryset(queryset=self.queryset)
        return queryset

    def __filter_queryset(self, queryset):
        user = self.request.user
        if user.user_type in [User.UserType.ADMIN, User.UserType.SUPER_ADMIN]:
            return queryset.all()
        elif user.user_type in [User.UserType.CUSTOMER, User.UserType.ARTIST]:
            return queryset.filter(pk=user.pk)
        return queryset

    @action(methods=['get'], detail=False)
    def me(self, request, pk=None):
        instance = request.user
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

**Comment by tfranzel** [comment] 2020-10-26 12:08
@KimSoungRyoul thanks for testing this. @Javedgouri i narrowed it down. i replaced the `*_fields` with the default fields, since we don't have your specific user model.

i believe your `__filter_queryset` is the culprit. it may provoke `django_filter` to throw an exception and then bail. please check if you have soemthings similar in your logs:

```venv/lib/python3.8/site-packages/django_filters/rest_framework/backends.py:147: UserWarning: <class 'tests.test_regressions.test_foo.<locals>.UserViewSet'> is not compatible with schema generation```

are you using the `CLI` or the `SpectacularSwaggerView`? the request may be mocked and only contain a `AnonymousUser`, for which those accesses (e.g. `user_type`) would fail.  you could do 

```python
if not self.request.user or not request.user.is_authenticated:
     return queryset.none()
```

to prevent exceptions

**Comment by tfranzel** [comment] 2020-11-04 23:03
@Javedgouri any luck on this? can we close the issue or is there a general problem

**Comment by Javedgouri** [comment] 2020-11-06 04:34
yes we can close this issue . Thank you @tfranzel

**Closed** 2020-11-06 09:30 UTC
Labels: question
