### ISSUE TITLE
Add support to Specification Extensions

### ISSUE THREAD

**Issue by jairhenrique** [tfranzel/drf-spectacular#165] opened 2020-10-11 14:17 UTC
https://swagger.io/specification/#specification-extensions

**Comment by tfranzel** [comment] 2020-10-11 15:19
hey @jairhenrique, can you give an example where this would be beneficial? extensions are very generic by nature and could be placed pretty much anywhere.

**Comment by jairhenrique** [comment] 2020-10-11 15:54
Hi @tfranzel I want do use this extra data to automate and document some steps on my deployment/environment. This feature will be useful to dev and ops team!

**Comment by tfranzel** [comment] 2020-10-11 16:03
i absolutely see the usefulness of this. the problem is that those extensions can in theory be used anywhere in the schema and we have no mechanism to freely place extensions.

how would we try to inject these extensions? `@extend_schema`? i'm a bit foggy on the details.

**Comment by jairhenrique** [comment] 2020-10-11 16:36
@tfranzel I need to take a better look on the source code. I don't know how to make it generic.

Does it make sense to have an object to represent it and some logic in the preprocess hooks?

```python
@extend_schema(
    specification_extensions=OpenApiSpecificationExtensions(
        data={
            'x-foo': 'bar', 
            'x-bar': {'a': 'b'}, 
            'x-node':1 
        }
    )
)
```


```python
SPECTACULAR_DEFAULTS = {
    "specification_extensions": OpenApiSpecificationExtensions(
        data={
            'x-foo': 'bar', 
            'x-bar': {'a': 'b'}, 
            'x-node':1 
        }
    )
}
```

**Comment by sdabhi23** [comment] 2020-12-18 16:11
We can maybe take the [extensions documentation](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md) published by Redoc as a starting point and then increase support as required. Some extensions like `x-traitTag` would go in `@extend_schema` and others like `x-logo` can be added to `SPECTACULAR_SETTINGS` in settings.py

What do you think @tfranzel ??

**Comment by tfranzel** [comment] 2020-12-20 14:12
generally i find the idea interesting. but i'm still hesitant on how to cleanly integrate this. as far as i can see those extensions can pop up everywhere and thus code would need to change in a lot of places. 

a lot of those redoc extensions are already part of 3.0.3 and are backported for older versions. at least that is what i understand.

sure, extensions like `x-logo` seem useful and are easy to patch into the info object. i'm more worried about providing a sane way to extensions in all other object types (tag, response, parameter, operation, schema), because some of them are not directly accessible through the provided spectacular decorators.

for small additions there are always [postprocessing hooks](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks) as a alternative. before really considering this as a core feature, i would like to see some really useful features we are missing out on.

@jairhenrique fyi, we included the examples feature a couple of days ago. some of your points might have also been addressed by [OpenApiExample](https://drf-spectacular.readthedocs.io/en/latest/readme.html#customization-by-using-extend-schema). let me know what you think.

**Comment by wattsin** [comment] 2021-01-20 04:19
@sdabhi23 this would be ideal, I realize adding all extensions does not make sense everywhere. But a few key ones in the SPECTACULAR_DEFAULTS defaults could be really useful. Like x-logo

**Comment by tfranzel** [comment] 2021-01-20 15:22
so the `info` section is easy as you said. tags is already covered by a setting. i'll have a look where we have low impact places to add this to. probably not a lot more.

**Comment by tfranzel** [comment] 2021-01-30 14:22
as discussed this gives an option for the info object. tags are already covered. due to the generic nature of extensions and the multitude of ways this could be employed, i hardly doubt we can go much further here without doing an incomplete and inconsistent feature.

i'll close the issue for now. if someone can come up with a really good concept here, we can most certainly revisit this.

**Closed by tfranzel** 2021-01-30 14:22 UTC

**Comment by allen-munsch** [comment] 2021-05-30 21:51
How to add logo to drf spectacular redoc

🚀🚀🚀🚀
```
SPECTACULAR_SETTINGS: Dict[str, Any] = {
    'EXTENSIONS_INFO': {
        "x-logo": {
            "url": "https://blahblah.cloudfront.net/static/img/logo-small.png",
            "backgroundColor": "#FFFFFF",
            "altText": "Nice NIce Logo"
        }
    },
}
```
🚀🚀🚀🚀

**Comment by tfranzel** [comment] 2021-10-01 16:02
vendors extensions are now supported (#540) with the excellent work of @ngnpope.

**Comment by jairhenrique** [comment] 2021-10-01 16:04
> vendors extensions are now supported (#540) with the excellent work of @ngnpope.

awesome!
