### ISSUE TITLE
Doesn't recognize django-filter lookup_expr lists

### ISSUE THREAD

**Issue by expresspotato** [tfranzel/drf-spectacular#239] opened 2020-12-23 01:09 UTC
Absolutely fantastic package @tfranzel 

One thing that I've found that makes tons of extra code is using the short hand filter expression (lookup_expr on a django-filters Filter) doesn't work. Only the original field is shown in parameters.

Example:

`amount = NumberFilter(lookup_expr=['exact', 'gt', 'lt'])`

Only results in the single field `amount` being shown in the schema. Instead multiple fields need to be added for reach filter:

```
amount__gt = NumberFilter(field_name='amount', lookup_expr='gt')
amount__lt = NumberFilter(field_name='amount', lookup_expr='lt')
...
```

While it's not a deal breaker, it makes our project messy over time... Since the lookup expressions are part of the field definition they should be available through introspection.

**Comment by tfranzel** [comment] 2020-12-23 10:27
hi @expresspotato, thank you so much.

interesting! i have not spent much time on `django-filter`. what you tell sounds interesting, but i cannot reproduce it in the tests unfortunately.

```python
price = NumberFilter(lookup_expr=['exact', 'gt', 'lt'])
```

this did nothing for me
```python
    # only one item with price 5 so expected outcome should ba zero objects
    response = APIClient().get('/api/products/?price__gt=8')  
    assert response.status_code == 200
    assert len(response.json()) == 0  # FAILS
``` 

as a matter of fact requesting ``/api/products/?price=8`` yielded

```
django.core.exceptions.FieldError: Unsupported lookup '['exact', 'gt', 'lt']' for FloatField or join on the field not permitted.
```

so even though your statement sounds reasonable, i cannot see the functionality in the `django-filter==2.4.0` for that. could you elaborate a bit more?

**Comment by tfranzel** [comment] 2021-01-09 17:31
@expresspotato i'll close this because the issue is idling. we can reopen if you can provide a working example, i.e. working with django-filter.

**Closed by tfranzel** 2021-01-09 17:31 UTC
