### ISSUE TITLE
Choice labels not showing in Swagger.

### ISSUE THREAD

**Issue by futilestudio** [tfranzel/drf-spectacular#679] opened 2022-03-14 14:22 UTC
**Describe the bug**

Labels of choices not showing in Swagger docs

- IntegerField, CharField
- TextChoices, IntegerChoices and also a plain list of tuples
 

**To Reproduce**
Not showing in Swagger auto docs

**Expected behavior**
It would make a big difference if we could also show labels of choices, not just their values. Is that possible?

**Comment by tfranzel** [comment] 2022-03-14 14:49
this is related to #337 (and #105). I totally get that this is a missing feature!

The problem is that OpenAPI 3.0.3 does not really provide a way to specify labels. Only hacks via the description string are possible at the moment. Not sure if OpenAPI 3.1 addressed that issue, but I believe I remember that it didn't yet.

We waited to see if there was some movement there before hacking together a non-standardized description string.

**Comment by tfranzel** [comment] 2022-03-28 10:41
closing in favor of #337. discussion continues there

**Closed by tfranzel** 2022-03-28 10:41 UTC
