### ISSUE TITLE
Examples in @extend_schema work only for 20X responses?

### ISSUE THREAD

**Issue by annawidera** [tfranzel/drf-spectacular#609] opened 2021-12-08 16:31 UTC
**Describe the bug**
When I am providing an explicit `OpenApiExample` it's being applied only to `200` and `201` responses. All other HTTP codes don't get that example. I observed the same behaviour when using `400: OpenApiResponse...`.

I am having function-based views and I am using `APIException` for notifying clients about errors. My idea was to provide possible errors as a set of `OpenApiExamples` before support for `APIException` as a kind of a response will be added. 

**To Reproduce**
``` Python 
@extend_schema(
  responses={
    400: OpenApiTypes.OBJECT
   },
   examples=[
      OpenApiExample(
          name="Example company details",
          summary="How the company details are returned",
          description="Getting company details",
          value={
              "ticker": "AAPL",
              "industry": "tecnología",
              "description": "company description",
          },
          response_only=True
      )
  ],
    methods=['PATCH']
)
@api_view(['POST', 'PATCH', 'DELETE'])
def manage_resource(request):
```

<img width="897" alt="image" src="https://user-images.githubusercontent.com/10179886/145244975-26cc36e4-f69c-4edc-b57d-501672b8fe10.png">

``` Python 
@extend_schema(
  responses={
    200: OpenApiTypes.OBJECT
   },
   examples=[
      OpenApiExample(
          name="Example company details",
          summary="How the company details are returned",
          description="Getting company details",
          value={
              "ticker": "AAPL",
              "industry": "tecnología",
              "description": "company description",
          },
          response_only=True
      )
  ],
    methods=['PATCH']
)
@api_view(['POST', 'PATCH', 'DELETE'])
def manage_resource(request):
```
<img width="889" alt="image" src="https://user-images.githubusercontent.com/10179886/145245043-3253723c-14c4-40ac-8f8d-1b20e3e94aeb.png">

**Expected behavior**
I would expect to see 
``` Python
value={
    "ticker": "AAPL",
    "industry": "tecnología",
    "description": "company description",
},
```
as an example for the `status code: 400`.

Am I doing something wrong? Thank you for any guidance!

**Comment by tfranzel** [comment] 2021-12-08 18:15
Hi,

this is by design. To prevent accidental mixing of regular and error examples, examples are scoped by default to `200` and `201`.

https://github.com/tfranzel/drf-spectacular/blob/57c1a3069ad560736c67995a35b39f32381ec7f3/drf_spectacular/utils.py#L120

For your case, you need to create the example with an explicit list of applicable status codes: `status_codes=[''400']`. If you do not care for the distinction above, just list all status codes `status_codes=['200', ...., '400']`.

**Comment by tfranzel** [comment] 2021-12-14 09:28
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-12-14 09:28 UTC
