### ISSUE TITLE
Schema Example Value not rendering correctly in Django project's Swagger UI

### ISSUE THREAD

**Issue by HadiMemar** [tfranzel/drf-spectacular#1192] opened 2024-02-29 15:59 UTC
**Describe the bug**
Schema Example Value not rendering correctly for some models in my Django Django project's Swagger UI, while the schema YAML file renders correctly in online Swagger viewers

**To Reproduce**
online swagger:
![image](https://github.com/tfranzel/drf-spectacular/assets/96471458/e4a480d2-1b11-482a-8e8e-5104be1315bf)
local swagger:
![image](https://github.com/tfranzel/drf-spectacular/assets/96471458/5d841f7f-463b-4c8c-9894-07cb31bd6f0e)

here it is returning "string" instead of the actual schema.
I thought it is an issue with my code, so I moved back to an old branch where I remember it was working fine, but same result.

**Expected behavior**
I expected the Swagger UI within my Django project to display the schema documentation accurately, as it does in online Swagger viewers. Specifically, I expected all models to be represented with their respective schemas in the example values, rather than displaying "string" for some models.

**Comment by tfranzel** [comment] 2024-02-29 16:30
Looks like a duplicate of https://github.com/tfranzel/drf-spectacular/issues/1186#issuecomment-1964096714

This is a bug in the latest SwaggerUI. Pin the version according to the comment.

**Comment by HadiMemar** [comment] 2024-02-29 18:08
> Looks like a duplicate of [#1186 (comment)](https://github.com/tfranzel/drf-spectacular/issues/1186#issuecomment-1964096714)
> 
> This is a bug in the latest SwaggerUI. Pin the version according to the comment.

thank you, it works now 😊

**Comment by tfranzel** [comment] 2024-02-29 21:15
i'll reopen this (for a short while) so people can see the issue on the top of the page:

Solution: https://github.com/tfranzel/drf-spectacular/issues/1186#issuecomment-1964096714

**Comment by tfranzel** [comment] 2024-03-04 23:43
resolved by new SwaggerUI release

**Closed by tfranzel** 2024-03-04 23:43 UTC
