### ISSUE TITLE
ViewSet.list endpoint response is always paginated

### ISSUE THREAD

**Issue by LowCostCustoms** [tfranzel/drf-spectacular#630] opened 2022-01-11 03:31 UTC
**Describe the bug**

DRF Spectacular doesn't let to fully customize `ViewSet.list` endpoint response schema and applies pagination over "schemas" defined in the endpoint responses. For example, if a custom serializer is specified in `extend_schema(responses=...)` decorator, the response schema will be rendered as:

```yaml
schema:
  type: array
  items:
    $ref: '#/components/schemas/ItemPage'
```

instead of:

```yaml
schema:
  $ref: '#/components/schemas/ItemPage'
```

**To Reproduce**

1. Create DRF `Serializers` and a `ViewSet` as follows:

```python
from drf_spectacular.utils import extend_schema
from rest_framework import status
from rest_framework.fields import IntegerField, CharField
from rest_framework.serializers import Serializer
from rest_framework.viewsets import ViewSet


class StuffSerializer(Serializer):
    name = CharField(read_only=True)
    id = IntegerField(read_only=True)


class StuffPageSerializer(Serializer):
    count = IntegerField(read_only=True)
    results = StuffSerializer(many=True, read_only=True)


class StuffViewSet(ViewSet):
    serializer_class = StuffSerializer

    @extend_schema(responses={status.HTTP_200_OK: StuffPageSerializer()})
    def list(self, request, *args, **kwargs):
        pass
```

2. Render OpenAPI spec with `python manage.py spectacular > docs.yaml`.
3. Ensure `StuffViewSet.list` endpoint response is defined as an array, i.e.:

```yaml
paths:
  /stuff/:
    get:
      operationId: stuff_list
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StuffPage'
```

**Expected behavior**

`pagination_class` is ignored if serializer is present in `extend_schema` or `extend_schema_view` annotation.

**Comment by tfranzel** [comment] 2022-01-11 10:53
Hi,

you mention `pagination_class` but your example does not use the actual pagination classes. However you are using your own pagination mechanism. Since you take over that responsibility, you can force `StuffPageSerializer` to be always flat:

```python
@extend_schema_serializer(many=False)
class StuffPageSerializer(Serializer):
    count = IntegerField(read_only=True)
    results = StuffSerializer(many=True, read_only=True)
```

Some explanation to why we do it like this. For the vast majority of cases `list` is indeed a list and thus we detect it as that. It only happens very rarely that you need to deviate from that. Your suggestion -- although not unreasonable -- would create a bunch of problems down the line.

FYI a test that builds a custom reusuable envelope. this might be useful to you: https://github.com/tfranzel/drf-spectacular/blob/57c1a3069ad560736c67995a35b39f32381ec7f3/tests/test_regressions.py#L698)

**Comment by LowCostCustoms** [comment] 2022-01-12 02:56
@tfranzel Ah, I see. Thanks, I'll give it a try!

**Comment by tfranzel** [comment] 2022-02-05 10:55
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2022-02-05 10:55 UTC
