### ISSUE TITLE
set responses parm for extend_schema will make auto-discovered query parameters disappeared

### ISSUE THREAD

**Issue by elonzh** [tfranzel/drf-spectacular#407] opened 2021-05-24 10:17 UTC
**Describe the bug**
set responses parm for extend_schema will make auto-discovered query parameters disappeared

**To Reproduce**

```python
...
    filterset_fields = {
        "id": ["in"],
        "foo": ["exact"],
    }
    filter_backends = [DjangoFilterBackend]

    @extend_schema(
        parameters=[
            OpenApiParameter(
                "format",
                OpenApiTypes.STR,
                location=OpenApiParameter.QUERY,
                required=True,
            )
        ],
        responses={(200, "*/*"): OpenApiTypes.STR},
    )
    def list(self, request, *args, **kwargs):
		...
```

**Expected behavior**

Auto-discovered query parameters exist as normal

**Comment by tfranzel** [comment] 2021-05-24 10:51
hi! is the parameter really missing? i can see the parameter in the operation, however i see a different issue. there happens some kind of name collision for the operation. i get `x_retrieve_2` instead of `x_list`.  can you confirm?

looks like the responses declaration creates that problem but i have to investigate.


```python
def test_viewset_list_override(no_warnings):
    class XViewset(viewsets.ReadOnlyModelViewSet):
        queryset = SimpleModel.objects.all()
        serializer_class = SimpleSerializer

        @extend_schema(
            parameters=[
                OpenApiParameter(
                    "format",
                    OpenApiTypes.INT,
                    location=OpenApiParameter.QUERY,
                    required=True,
                )
            ],
            responses={(200, "*/*"): OpenApiTypes.STR},
        )
        def list(self, request, *args, **kwargs):
            pass  # pragma: no cover

    schema = generate_schema('/x', XViewset)
    assert schema['paths']['/x/']['get']['parameters'][0]['name'] == 'format' # OK
    assert schema['paths']['/x/']['get']['operationId'] == 'x_list'  # FAIL
    assert schema['paths']['/x/{id}/']['get']['operationId'] == 'x_retrieve'  #FAIL
```

**Comment by tfranzel** [comment] 2021-05-24 11:20
so it turns out that you override the list detection by doing `OpenApiTypes.STR`, which is obviously not a list. this then generates a `x_retrieve` name instead of `x_list`. then you get a collision for 2 `x_retrieve` in that viewset.

we cannot change this, as it breaks a dozen other things. what you can do is set an explicit `operationId='x_list'`, which prevents the collision from happening. then everything should be as expected. you basically undo the (name) change that resulted from your `responses=...`.

**Comment by elonzh** [comment] 2021-05-25 03:03
Set an explicit operationId='x_list' is not working, the `_get_filter_parameters` will detect the view type and it will be return a False if the response `is_basic_type`.

So this is definitely a bug.

```
    def _get_filter_parameters(self):
        if not self._is_list_view():
            return []
```

**Comment by tfranzel** [comment] 2021-10-17 11:31
So I had another look and I think I now have a better undestanding of the problem. It is a bit of an unfortunate situation though.

Any changes to `_is_list_view` will likely break a lot of people. For better or worse we are stuck with the heuristic as is. However it works as expected here because the response is indeed not a list.

It is true that `filter_queryset` is also applied to `retrieve`. However, we made the simplifiying assumption that filters usually only make sense for lists (e.g. pagination). I imagine it to be very confusing having all those `django-filters` on **all Viewset methods** (retrieve, list, patch, put) all the time by default. Given that this has only come up twice in 2 years, I assume for most users this currently works just as they would expect.

Imho the problem is that we currently have no way of enabling the detected filters (not manually defined) when the response is clearly not a list. So basically a selective way to disable our "simplifiying assumption".

The `operation_id` is only partially relevant here as it is more of a side effect.

**Comment by tui95** [comment] 2021-10-17 11:51
Thanks for the response. That's unfortunate though.

**Comment by tfranzel** [comment] 2021-10-17 11:59
Not saying we won't fix it! Actually I think its not too bad. We can fix this. It's just not going to be an "automatic" fix, but that is not really a issue since your are already doing something manually by using `@extend_schema`.

**Comment by tfranzel** [comment] 2021-10-18 14:25
```python
        @extend_schema(
            responses={(200, 'application/pdf'): OpenApiTypes.BINARY},
            filters=True,
        )
```

is the preferred way to enable filters for non-list responses. This can also be used as suppression with `False`.

This does not touch list detection itself, since spectacular imho does the right thing here already. `OpenApiTypes.BINARY` is by definition not a list. By default the filters stay coupled to list detection, as this does the right thing for the vast majority of cases. 

Depending on your case, you may also need the `operation_id` override to prevent the warning. This is intended behavior and is orthogonal to this issue.

**Comment by tfranzel** [comment] 2021-11-10 16:38
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-11-10 16:38 UTC
Labels: enhancement, fix confirmation pending
