### ISSUE TITLE
Wrapping serializer data in a response dict

### ISSUE THREAD

**Issue by AqeelAT** [tfranzel/drf-spectacular#463] opened 2021-07-22 15:33 UTC
Hi,

Most of our views return the following results in the following format:
```
Response(
    {"result": serializer.data, 'message': 'Loaded successfully', 'status': True},
    status=200
)
```
What's the best way to include that in the generated schema? I was able to do it via inline_serializer, but is there a way to do it en masse? Like, via a setting that says surround all returned serializers in another serializer.

**Comment by tfranzel** [comment] 2021-07-23 08:00
Hi,

this is a special have we have dealt with before in issue #49 

there is a relatively elegant workaround for these cases: https://github.com/tfranzel/drf-spectacular/blob/eb02752cc194afaf246788c7604bc40f072e0044/tests/test_regressions.py#L698

for a global solution i would have to give it some more thought

**Comment by tfranzel** [comment] 2021-07-28 08:23
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-07-28 08:23 UTC

**Comment by johnbridstrup** [comment] 2022-12-10 01:03
I am also interested in a general solution to this. I have seen #49

**Comment by tfranzel** [comment] 2022-12-10 13:14
This should get you pretty close. The enveloper helper is exactly the same. You just need to write a custom  `AutoSchema` to apply this change to every response. 

Remember to change `DEFAULT_SCHEMA_CLASS ` to your `CustomAutoSchema`

```python
from drf_spectacular.plumbing import get_class

def enveloper(serializer_class, many):
    component_name = 'Enveloped{}{}'.format(
        serializer_class.__name__.replace("Serializer", ""),
        "List" if many else "",
    )

    @extend_schema_serializer(many=False, component_name=component_name)
    class EnvelopeSerializer(serializers.Serializer):
        status = serializers.BooleanField()  # some arbitrary envelope field
        data = serializer_class(many=many)  # the enveloping part

    return EnvelopeSerializer

class CustomAutoSchema(AutoSchema):
    def get_response_serializers(self):
        """ use envelope on all default responses. @extend_schema will override this change """
        serializer_class = get_class(self._get_serializer())
        return enveloper(
            serializer_class=serializer_class,
            many=self._is_list_view(serializer_class)
        )
```

**Comment by johnbridstrup** [comment] 2022-12-11 01:51
Thank you! Very helpful A+

**Comment by shalushaji** [comment] 2024-04-18 07:37
@tfranzel The enveloper works properly. But it is missing the paginated response. Outer fields are properly shown, but the paginated answer is missing. May be because of explicitly mentioned the serializer_class` in the `EnvelopeSerializer`.
