### ISSUE TITLE
Help Request: Is it possible to use custom named actions?

### ISSUE THREAD

**Issue by petasis** [tfranzel/drf-spectacular#647] opened 2022-02-01 18:51 UTC
Hi all,

I have created a class, that inherits APIView. This class does some extra functions (like logging exceptions, etc.), and finally it delegates the get/post/put/patch/delete methods to list/retrieve/create/destroy.

Classes that inherit my class, implement the list/retrieve/create/destroy methods. However, the documentation is empty for these methods, as drf-spectacular looks only for get/post/put/patch/delete, if the class inherits APIView.

Is there a way to convince drf-spectacular to use instead my new methods list/retrieve/create/destroy?

**Comment by tfranzel** [comment] 2022-02-01 19:53
Hi @petasis, this has been answered in the FAQ: https://drf-spectacular.readthedocs.io/en/latest/faq.html#using-extend-schema-on-apiview-has-no-effect

This by design and the only right thing to do. For `APIView`, DRF will only call `get()/post()/...` and **does not care** in the slightest that there is also a `list()/retrieve()/...` method. The `get()` will get proxied to `list/retrieve` if you use DRF's `Mixin`s but that is just an implementation detail that you could choose to do totally differently. 

We only look for and parse what DRF will use as the outer-most entrypoint. I know this might feel weird, but that is what DRF is doing internally and using anything else would be brittle and potentially wrong.

**Comment by tfranzel** [comment] 2022-02-09 19:52
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2022-02-09 19:52 UTC
