### ISSUE TITLE
Type warning from ReadOnlyField exposing `get_FOO_display`

### ISSUE THREAD

**Issue by mikaraunio** [tfranzel/drf-spectacular#1228] opened 2024-04-30 20:22 UTC
Django provides a built-in `get_FOO_display` method to display the human-readable value of fields with `choices`. If a serializer exposes this value via a `ReadOnlyField`, drf-spectacular generates this slightly cryptic warning:

```
unable to resolve type hint for function "_method". Consider using a type hint or @extend_schema_field. Defaulting to string.
```

This is harmless since `get_FOO_display` is guaranteed [^1] to return a string, but would be nice to silence the warning.

Using `CharField` with `read_only=True` works around this, but is slightly more wordy, and less explicit.

**To Reproduce**

```python
class MySerializer(serializers.ModelSerializer):
    mychoicesfield_display = serializers.ReadOnlyField(source='get_mychoicesfield_display')
```

[^1]: https://github.com/django/django/blob/main/django/db/models/base.py#L1269

**Comment by tfranzel** [comment] 2024-05-07 08:45
Hi @mikaraunio,

good find! This was unhandled before. I think it is fair to assume string, even though it is a implementation detail and not strictly guaranteed. Still way better that before.

**Comment by mikemanger** [comment] 2024-05-31 16:13
This happens with when the source is set to `'__str__'` also.

**Comment by tfranzel** [comment] 2024-05-31 17:33
@mikemanger interesting. To my surprise that seems to be legal and working. However, I find this to be dangerous because it may potentially leak internals. Not a fan adding another hack for this. Also for consistency, we would need to add hacks for dunders like `__repr__` and so on. 

If you really want to do this, add a ` -> str` hint to `__str__` and spectacular should pick it up.

**Comment by mikemanger** [comment] 2024-06-03 08:48
`__str__()` is for endusers, [overriding it works nicely with Django in a few places](https://docs.djangoproject.com/en/5.0/ref/models/instances/#str). But I agree with your concerns.

**Comment by tfranzel** [comment] 2024-06-03 14:22
@mikemanger I just confirmed that type hinting the `__str__` method will fix the issue. I think that is an acceptable compromise. 

I see the usage of that method mainly in the admin and internal. I would be surprised to see an implicit model instance representation exposed through the REST API like that, but that may be just me.

I'll close the issue since this was implemented. I'm trying to make time for a new release soon.

**Closed by tfranzel** 2024-06-03 14:22 UTC

**Comment by flc** [comment] 2024-07-03 14:57
I expose the `get_FOO_display` of choice fields a lot in the API since it provides a human readable value, and I also get the above mentioned warnings. It would be great to get rid of them.
When you say "type hinting the `__str__ `" what do you mean exactly? The `get_FOO_display` methods come from Django side, they are not specified in the model classes directly.

**Comment by tfranzel** [comment] 2024-07-03 16:20
@flc so this fix is not released yet, which is you get the error. Things like `ReadOnlyField(source='get_mychoicesfield_display')` should work now on master. I'll try to do a release as soon as I find the time.

the question regarding `ReadOnlyField(source="__str__") is only indirectly related. If you want to use the `__str__` of the model, you need to type hint the `__str__` function.

**Comment by flc** [comment] 2024-07-04 08:06
@tfranzel I checked master, and indeed, those warnings are gone.
I hope you can find the time for a new release soon, thank you!
