### ISSUE TITLE
Automatically resolve identical serializer names by fully qualified class path

### ISSUE THREAD

**Issue by haerrel** [tfranzel/drf-spectacular#976] opened 2023-04-17 10:26 UTC
## Description
What is the intended way how to solve serializer name collisions? I propose to automatically resolve identical serializer names by fully qualified class path for open-api schema generation. #51 already discussed this, but i couldnt find a implementation or how to use it.

## Use Case
The warning we encounter:
```
.../workspace/a/b/c/d/serializers.py:25: Warning [DViewSet > ResponseSerializer]:
Encountered 2 components with identical names "Response" and different classes <class 'a.b.c.d.serializers.ResponseSerializer'> and <class 'a.b.c.e.serializers.ResponseSerializer'>. This will very likely result in an incorrect schema. Try renaming one.
```

In our project we have many idential serializer names, due to the following reasons:

* We have separate response and request serializers for every endpoint. Therefore we have many serializers named `ResponseSerializer` and `RequestSerializer`.
* All serializers are independent and are not shared with other serializers. As by convention we use the model name for the serializer name (`{Modelname}Serializer`). Therefore we have multiple serializers for one model.

Renaming serializers is not an option, due to the amount of serializers.

## Proposed Solution
like in #51 discussed one could use qualname

for now i am running on a fork where i changed [this line](https://github.com/HospiChef/drf-spectacular/blob/6fdaa499bb36e87dda233d51d7c60a6ac37e1021/drf_spectacular/openapi.py#L1541) 

## Related Issues

#606 - recommends `@extend_schema_serializer(component_name='ABC')` to rename serializers, this is unsuitable if there are many serializers that need to be renamed
#90 - recommends the `ref_name`, but this needs to be applied to all serializers
#51 - talks about implementing what i am asking for, but i couldnt find that it ever got implemented?
#27 - suggests to use OpenApiSerializerExtension, but this needs to be applied to all serializers

**Comment by tfranzel** [comment] 2023-04-17 11:39
Hi @haerrel 

I recognize that this is still a problem, although only for a minority of users with a specific kind of project setup. It is important to address this nonetheless.

#51 deals mainly with Enum naming, for which there is no unique corresponding class to draw a name from. There were a lot of confusing, semi-wrong statements in that issue. I get that the proposed solution looks similar, but the problem is different.

The related issues all address one-off issues. Of course your issue is structural and so those solutions do not really help you here.

I'm contemplating introducing a callable like the `SORT_OPERATIONS` setting. That is, the current default, maybe a module naming option and a manual callable option, because I can already see this not being enough for some people.

**Comment by nenkoru** [comment] 2023-07-04 11:35
+1 for the issue
Having the same hard time dealing with the samely named serializers within views

**Comment by tfranzel** [comment] 2023-07-09 16:05
So I decided to make this a bit easier to customize. There will be no out of the box solution as everybody has different requirements here and there is simply no one-size-fits-all solution, however we can ease the customization.

You will need to write a small customized Schema class and point the settings to it. Here is an example on how to do it. I'll leave the exact module name extraction to you guys.

The commit just introduces `get_serializer_name` which only deals with the name. The existing `_get_serializer_name` will only deal with the related plumbing. So overriding is now "easier".


```python
# project/schema.py
from inflection import camelize
from drf_spectacular.openapi import AutoSchema


class CustomAutoSchema(AutoSchema):
    def get_serializer_name(self, serializer, direction):
        # extract some camelized module path name without dots.
        module_prefix = camelize('Foo.Bar.Baz'.replace('.', ''))

        return f"{module_prefix}{serializer.__class__.__name__}"


# settings.py
REST_FRAMEWORK = {
  'DEFAULT_SCHEMA_CLASS': 'project.schema.CustomAutoSchema',
}
SPECTACULAR_SETTINGS = {
  # distinguish request/response in components automatically
  'COMPONENT_SPLIT_REQUEST': True,
}
```

**Comment by tfranzel** [comment] 2023-07-09 16:33
@haerrel so my rational for this is that I won't even attempt to make this opinionated for everyone. Some people might only want the partial module path to show up, other might not like dots there, other would like to have a different formatting, etc etc. I can literally guarantee that not everyone will be happy with `__class__.__module__`. Futhermore, changing the default and thus breaking every existing schema for this is a big nono anyway.

I think this is the most portable solution that makes it easy for everyone to have the name as they desire without reinventing the wheel or needlessly breaking peoples deployments.

This will be released sometime next week.

**Closed** 2023-07-23 21:20 UTC
Labels: enhancement, fix confirmation pending
