### ISSUE TITLE
"title" keyword missing when it is equal to verbose_name

### ISSUE THREAD

**Issue by chgad** [tfranzel/drf-spectacular#948] opened 2023-02-27 10:19 UTC
**Describe the bug**

Defining a django model field with a verbose_name that does only differ in capitalization from the fieldname will result in missing the `"title"` keyword in the schema.

**To Reproduce**
Consider the following model/serializer:

``` python
class TestModel(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))

class TestModelSerializer(serializer.ModelSerializer):

        class Meta:
            model = TestModel
            fields = "__all__"

```

The schema generated is:

```yaml
    TestModel:
      type: object
        name:
          type: string
          maxLength: 200
```

**Expected behavior**

I'd expect the title to be present wether the `verbose_name` is equal to the field name or not.

```yaml
    TestModel:
      type: object
        name:
          type: string
          title: "Name"
          maxLength: 200
```

INFO: 

I searched the OpenAPI Specification, the [JSON Schema validation](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00) and the [JSON Schema](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00) mentioned in it.
The result: This behavior is not mentioned anywhere.

Was it intended by design or is it an actual bug?

**Comment by tfranzel** [comment] 2023-02-27 10:35
yes, this is more or less intended behavior. DRF injects the field name as  `verbose_name` by default. To reduce duplication we remove those. Unfortunately, we cannot distinguish user input from DRF auto defaults. 

Not having a verbose name that is already the name should only be a minor inconvience, given that it adds no information by definition. It is a reasonable trade-off imho.

https://github.com/tfranzel/drf-spectacular/blob/b779366b224e8a08b763fd5c1039bf9cd506b01d/drf_spectacular/openapi.py#L737-L740

**Comment by chgad** [comment] 2023-02-27 10:44
> Not having a verbose name that is already the name should only be a minor inconvience, given that it adds no information by definition. It is a reasonable trade-off imho.

I understand the argument about duplication. Yet it makes the output sort of inconsistent and unexpectable to parse automatically.

The reasoning is logically and I can live with it ( and amending our parser is okay) but could we document this decision somewhere? In the end it is a `drf-spectacular` decision, not OpenAPI specifc.

**Comment by tfranzel** [comment] 2023-02-28 17:06
> I do not want to start a fundamental debate about it now on the contrary

no worries, me neither. 😄 

> None the less it is inconsistent (showing variety in accordance to a known rule set/concept) as long as the design choices are unknown/difficult to discover

The thing is that disecting DRF to build a OpenAPI schema is all but straight-forward. For the most part, there is no singular path on how to build the individual schema parts. So by nature of the problem, almost every aspect of this is opinionated. You could call drf-spectacular a collection of (mostly my) strong opinions. It will be hard to write down.

> I'd be happy to start contributing in this topic since imho it is important to somewhat note which decisions where made.

sure, good doc is always nice to have. The tricky part is providing it in a digestible fashion. I just want to point out that this additional information should not distract the user. 

For a user that just wants a working schema (like probably most do), those details are most certainly just added noise. I'm assuming that the average user neither cares nor wants to know these implementation details. 

If you want collect those details in a separate doc section, I'm happy to look at your proposal.

**Comment by tfranzel** [comment] 2023-03-02 10:19
i'll close this as the title is misleading, but feel free to open a PR or another issue for documenting implementation details.

**Closed by tfranzel** 2023-03-02 10:19 UTC
