### ISSUE TITLE
DRF generic error response in schema

### ISSUE THREAD

**Issue by tomas-hanzlik** [tfranzel/drf-spectacular#220] opened 2020-11-30 19:02 UTC
I would like to have the structure of generic DRF errors in the generated schema but so far no success. Specifically, show the structure of `ValidationError` with a custom description like `List of validation errors not related to any field`.

Basically the same as here: https://github.com/axnsan12/drf-yasg/issues/224

Is there a way how to do it? Thank you!

**Comment by tfranzel** [comment] 2020-12-01 00:58
Hi! error declaration is not yet supported but on the my roadmap. i think #101 more generally addresses this.

**Comment by thanzlik** [comment] 2020-12-01 01:12
Hi @tfranzel , thank you for your time and for the clarification! :)

**Comment by tfranzel** [comment] 2020-12-08 12:18
duplicate of #101

**Closed by tfranzel** 2020-12-08 12:18 UTC

**Comment by sourabhtkd** [comment] 2022-03-28 06:18
add NON_FIELD_ERRORS_KEY in settings.py as per https://www.django-rest-framework.org/api-guide/exceptions/.
For 500 or any unexpected errors write a custom exception handler, when exception is raised then log the exception and return your generic response
