### ISSUE TITLE
many=True inconsistent behavior for non-200 status_code

### ISSUE THREAD

**Issue by jerinpetergeorge** [tfranzel/drf-spectacular#402] opened 2021-05-22 05:57 UTC
Consider I have a view as below,
```python
# serializers.py
class EmptyPayloadResponseSerializer(serializers.Serializer):
    detail = **serializers.CharField()


# views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from drf_spectacular.utils import extend_schema
from .serializers import EmptyPayloadResponseSerializer


class EmptyPayloadAPI(APIView):
    @extend_schema(responses=EmptyPayloadResponseSerializer(many=True))
    def post(self, request, *args, **kwargs):
        # some actions
        return Response(data={"detail": "Success"})
```

_Specifically, focus on the `responses=EmptyPayloadResponseSerializer(many=True)` statement_

I have got the [expected behavior](https://user-images.githubusercontent.com/21334929/119216181-c29dbe80-baef-11eb-9c01-a1eff7776c98.png)
```json
[
  {
    "detail": "string"
  }
]
```

So fo so good!!!

Then, I have changed the `responses` parameter as,
```python
from rest_framework.views import APIView
from rest_framework.response import Response
from drf_spectacular.utils import extend_schema
from .serializers import EmptyPayloadResponseSerializer


class EmptyPayloadAPI(APIView):
    @extend_schema(
        responses={
            200: EmptyPayloadResponseSerializer(many=True),
            400: EmptyPayloadResponseSerializer(many=True),
        }
    )
    def post(self, request, *args, **kwargs):
        # some actions
        return Response(data={"detail": "Success"})
```

and I have got the schema as,
![image](https://user-images.githubusercontent.com/21334929/119216273-6d15e180-baf0-11eb-92f0-797794d6e223.png)

Is this the intended behavior? :thinking:

**Comment by tfranzel** [comment] 2021-05-22 10:15
hey! yes we changed that on purpose. the other argument is in #277. the rationale was that responses in the error range (`X<200 && X>= 300`) are usually not paginated, filtered or listed. i figured that this is simply more common compared to your use-case.

i have to investigate if it is possible to honor that `many=True` there for `400`.

**Comment by ConnorLanglois** [comment] 2021-07-22 18:18
@tfranzel I am also having this same issue. Is there perhaps an estimation on when a fix for this will be pushed out or any guidance you could give for anyone looking to make a PR to fix this, such as where in the code we can find this behavior? Also, in the meantime, is there any workaround we can apply?

**Comment by tfranzel** [comment] 2021-07-23 11:38
regarding my earlier comment: 

> i have to investigate if it is possible to honor that many=True there for 400.

pretty certain at this point that it is not possible make it do the right thing by design. DRF simply does not provide enough information for us at this point to make a more educated decision.

@ConnorLanglois : i'll look into it again, but a setting is the most likely outcome. can't see any other way to serve both use-cases.

**Comment by tfranzel** [comment] 2021-07-23 12:48
@ConnorLanglois @jerinpetergeorge introduced a new setting to choose the behavior. default is the current behavior.

**Comment by ConnorLanglois** [comment] 2021-07-23 13:10
@tfranzel Nice work man! Really appreciate the hard work and fast response time. Yeah that setting looks perfect, any clue on when next release is?

**Comment by tfranzel** [comment] 2021-07-23 13:21
thanks! got one more issue to look at after which i will do a release.

**Closed** 2021-07-28 08:25 UTC
Labels: bug, fix confirmation pending
