### ISSUE TITLE
Hello, while some of the example values work perfectly fine, I don't know why some of them don't show correctly.

### ISSUE THREAD

**Issue by amirsalmanii** [tfranzel/drf-spectacular#1195] opened 2024-03-03 12:17 UTC
![Screenshot from 2024-03-03 15-45-46](https://github.com/tfranzel/drf-spectacular/assets/52850239/437ca983-e3b6-4b66-82f0-f8f384179e45)
in this case schema detected but example value is wrong

but 90% of others is correct
my code:
`
class AuthLoginRegisterApiView(APIView):
    class LoginRegisterInputSerializer(serializers.Serializer):
        custom_error = None
        phone_number = serializers.CharField()

        def validate(self, attrs):
            if len(attrs.get("phone_number")) != 11:
                self.custom_error = PHONE_NOT_VALID.results
            return super().validate(attrs)

    @extend_schema(
        request=LoginRegisterInputSerializer,
        responses=ReturnMessageSerializer,
        tags=["authentication"],
    )
    def post(self, request):
        serializer = AuthLoginRegisterApiView.LoginRegisterInputSerializer(
            data=request.data
        )
        if serializer.is_valid() and serializer.custom_error is None:
            return Auths.start_otp(data=serializer.data)
        return serializer.custom_error
`

**Comment by codeofmagma** [comment] 2024-03-04 04:20
Same for me, looks like floating bug in UI components. Sometimes bug may disappear after few swagger page reloads, but sometimes it doesn't. Doesn't depend on http method (works for GET, PATCH, POST), doesn't depend on request or response part of docs.

**Comment by tfranzel** [comment] 2024-03-04 09:43
duplicate of #1192

This is a SwaggerUI bug. It was supposedly fixed 45 minutes ago with [5.11.9](https://github.com/swagger-api/swagger-ui/compare/v5.11.8...v5.11.9) https://github.com/swagger-api/swagger-ui/releases

**Closed** 2024-03-04 23:42 UTC

**Comment by amirsalmanii** [comment] 2024-03-05 07:34
> duplicate of #1192
> 
> This is a SwaggerUI bug. It was supposedly fixed 45 minutes ago with [5.11.9](https://github.com/swagger-api/swagger-ui/compare/v5.11.8...v5.11.9) https://github.com/swagger-api/swagger-ui/releases

tnx
So if this package is release update, will everything be fixed?
