### ISSUE TITLE
help_text defined on model is overridden with empty help_text from serialiser level

### ISSUE THREAD

**Issue by diego351** [tfranzel/drf-spectacular#942] opened 2023-02-20 10:44 UTC
**Describe the bug**
Valid help_text defined on model fields are overridden with empty help_text from serialiser level

**To Reproduce**

```
class Brand(models.Model):
    image = models.ImageField(blank=True, upload_to="images", help_text='Wanted help_text')

class BrandSerializer(ModelSerializer):
    from drf_extra_fields.fields import Base64ImageField
    image = Base64ImageField(required=False)
   
    class Meta:
        model = Brand
        fields = ('id', 'image')

class BrandListView(ListAPIView):
    model = Brand
    serializer_class = BrandSerializer
    pagination_class = LimitOffsetPagination
    queryset = model.objects.all()

```
produces:

```
 Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image:
          type: string
          format: uri # <- no description
      required:
      - id
```
  

**Expected behavior**

help_text on model level shouldn't be overridden with empty help_text on serialiser level. These help_text will makes sense for most of the cases. They should only be overridden if explicitly defined on serialiser level.  Other examples of unwanted overriden help_text: https://github.com/tfranzel/drf-spectacular/issues/941#issuecomment-1435975449

Please don't close the issue right away, let the people have their vote.

**Comment by tfranzel** [comment] 2023-02-20 11:25
This is a duplicate of #941. 

As discussed there, this is how OO and DRF `ModelSerializer` work. If you manually overwrite a `ModelSerializer` field (`image`), you loose the amenities of the original auto-generated field. 

There is no sane reason to pull that `help_text`, given that you have created a completely different field instance (`Base64ImageField`) for `image`.

**Closed** 2023-03-04 17:38 UTC
