### ISSUE TITLE
DRF 3.10 Compatibility

### ISSUE THREAD

**Issue by mardukery** [tfranzel/drf-spectacular#812] opened 2022-09-21 21:56 UTC
**Describe the bug**
I believe the current version of spectacular only supports DRF 3.10.3 and above. 
I am using 3.10.0 as per the [requirements](https://drf-spectacular.readthedocs.io/en/latest/readme.html#requirements).
I was getting an error:
`File "...site-packages/drf_spectacular/openapi.py", line 1371, in _get_response_for_code
    schema=paginator.get_paginated_response_schema(schema),
AttributeError: 'PageNumberPagination' object has no attribute 'get_paginated_response_schema'`
This method appears to have been added [here](https://github.com/encode/django-rest-framework/commit/f8c16441fa69850fd581c23807a8a0e38f3239d4) on 09/03/2019. 
3.10.3 was released the [next day,](https://pypi.org/project/djangorestframework/#history) and I assume is the first version with the new code
**To Reproduce**
See line: /drf_spectacular/openapi.py", line 1371, in _get_response_for_code
    schema=paginator.get_paginated_response_schema(schema)
This method does not exist until DRFv3.10.3
**Expected behavior**

**Comment by tfranzel** [comment] 2022-09-22 00:04
Hi, this is a duplicate of #791. You are correct, we only support DRF 3.10.3 and above. This only came to light recently and the requirements were not changed accordingly. If you want to use the pagination, I would urge you to update to 3.10.3. There is not a good workaround for it.

> I am using 3.10.0 as per the [requirements](https://drf-spectacular.readthedocs.io/en/latest/readme.html#requirements).

We did not explicitly state support for 3.10.0. Usually it is customary that only the latest patch releases are officially supported. DRF does the same with Django and Python. But I admit it is a bit fuzzy. I'll update the readme.

Is there any reason to not go from 3.10.0 to 3.10.3? The dot release should not break reverse-compatibility and does only contain bugfixes.

**Closed** 2022-10-05 12:43 UTC
