### ISSUE TITLE
Separate settings for APIs

### ISSUE THREAD

**Issue by firstgeneration** [tfranzel/drf-spectacular#627] opened 2021-12-30 21:13 UTC
Hi, thanks for this awesome library! I have two separate APIs in my project, and would like to maintain separate `spectacular_settings` for each. Since I cannot do that from the user `SPECTACULAR_SETTINGS`, how can I attach the separate settings dict to each generator, for them both to coexist?

**Comment by tfranzel** [comment] 2021-12-30 21:25
Hi, this is a duplicate of #365. The feature is part of the most recent version:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#how-can-i-have-multiple-spectacularapiview-with-differing-settings

**Comment by tfranzel** [comment] 2022-01-04 12:50
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2022-01-04 12:50 UTC

**Comment by firstgeneration** [comment] 2022-01-04 23:28
Thank you for following up. `custom_settings` has come in handy when generating via views. I'd like to pass settings to the management command as well , is there a workaround for that too? `./manage.py spectacular --generator-class=module.class.CustomAPISchemaGenerator`
