### ISSUE TITLE
NameError for model imported within TYPE_CHECKING clause

### ISSUE THREAD

**Issue by mblayman** [tfranzel/drf-spectacular#390] opened 2021-05-18 16:07 UTC
**Describe the bug**

While annotating a view with something like:

```python
    @extend_schema(
        responses=PolymorphicProxySerializer(
            component_name='MetaSerializer',
            serializers={
                "foo": SerializerA,
                "bar": SerializerB,
                "baz": SerializerB,
            },
            resource_type_field_name='char_field_on_serializer',
        )
    )
    def get(self, request: Request, *args: Any, **kwargs: Any) -> Response:
        return super().get(request, *args, **kwargs)
```

There was a `NameError` when trying to resolve a field's type hints.

```python
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/management/commands/spectacular.py", line 50, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/generators.py", line 230, in get_schema
    paths=self.parse(request, public),
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/generators.py", line 207, in parse
    operation = view.schema.get_operation(path, path_regex, method, self.registry)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/utils.py", line 222, in get_operation
    return super().get_operation(path, path_regex, method, registry)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 975, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200')}
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 1013, in _get_response_for_code
    component = self.resolve_serializer(serializer, 'response')
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 1152, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 673, in _map_serializer
    schema = serializer_extension.map_serializer(self, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/serializers.py", line 15, in map_serializer
    sub_components = self._get_explicit_sub_components(auto_schema, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/serializers.py", line 54, in _get_explicit_sub_components
    resolved_sub_serializer = auto_schema.resolve_serializer(sub_serializer, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 1152, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 675, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 742, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 621, in _map_serializer_field
    return append_meta(self._map_response_type_hint(method), meta)
  File "/usr/local/lib/python3.6/site-packages/drf_spectacular/openapi.py", line 801, in _map_response_type_hint
    hint = get_override(method, 'field') or typing.get_type_hints(method).get('return')
  File "/usr/local/lib/python3.6/typing.py", line 1543, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/local/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/usr/local/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'TheDjangoModel' is not defined
```

In this code snippet, `SerializerA` and `SerializerB` subclass from a parent serializer defined in another module. That parent serializer references `TheDjangoModel` in the type signature. In that signature, `TheDjangoModel` is in a string form and the import is guarded by `TYPE_CHECKING` to avoid issues with circular imports with the Django app.

**Expected behavior**

I would expect that `TheDjangoModel` would resolve. When I run the same code through mypy, there are not name resolving problems.

If you'd like more context, I'm happy to supply it.

**Comment by tfranzel** [comment] 2021-05-18 17:00
hi, i think we need a bit more context. 

we use `typing.get_type_hints` from the std lib to extract types. according to the doc that function does resolve type strings, which i just confirmed.  

i'm not sure it is even viable for us to run with `TYPE_CHECKING` as we do call methods and so on.

**Comment by mblayman** [comment] 2021-05-19 14:19
ok, I'll try to dig into the exception more and get back to you. Maybe it's a manifestation of a circular import.

Is there a way to delay the evaluation until a later time? With `extend_schema` as a method decorator, that evaluation is at module import time. I'm wondering if that might be causing an issue in this circumstance.

**Comment by tfranzel** [comment] 2021-05-19 17:30
looks like you are using the CLI. everything is already pretty lazy and stuff happens only when needed. the trace tells me that this happens when the schema is generated and not when `extend_schema` is processed. there is no way around having the model at generation time. seems like something else is weird imho.

**Comment by tfranzel** [comment] 2021-05-31 15:14
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-05-31 15:14 UTC

**Comment by mblayman** [comment] 2021-05-31 15:28
Sorry for letting this hang around. I haven't had to time to dig into this more. This API endpoint is one of the last hold outs for my team have an entirely documented API so I'll try to report back with my findings later if I can.

**Comment by tfranzel** [comment] 2021-05-31 15:43
sure thing. we'll reopen this if you have more insight. 

it sure is a satisfying thing having a fully and automatically documented API.

**Comment by YPCrumble** [comment] 2022-10-15 17:08
I'm having the same issue with a model method that includes a type hint like this pseudo-code:

```
if typing.TYPE_CHECKING:
    from another_module.models import MyModel


class AnotherModel:
    def get_something(self, my_model: "MyModel" = None):
        if my_model is None:
            return "something"
        return "something else"
```

My serializer is calling `get_something` by including `get_something` in the `fields` attribute.

The error is:

> NameError at /api/schema/ name 'MyModel' is not defined

As noted above it's in the `typing.get_type_hints` function being called on this model method.

It appears that there's a workaround, https://github.com/python/typing/issues/797#issuecomment-814364289, which also appears to have a bug, but perhaps adding `localns=locals()` could help avoid this error. I can confirm that most of my models are included in `localns` but `MyModel` is not, and this repo's call to `get_type_hints` doesn't seem to specify `localns`.

My current workaround is to simply remove the offending type hint. 

Thanks for maintaining this repo and for raising this isssue! Happy to help debug further if that's helpful.

**Comment by tfranzel** [comment] 2022-10-15 17:24
@YPCrumble you problem might be a different issue. the `if typing.TYPE_CHECKING` branch is only executed when mypy is run. Since spectacular does not run independently, it is subject to the regular environment. Thus `MyModel` is simply not imported during regular execution. Not sure if your reference issue even plays a significant role here.

The quoting of types itself should not be a problem. There are differences between python version here though

**Comment by wilson0x4d** [comment] 2024-08-31 08:39
this issue comes up for me as a top result on google for this error.

> My current workaround is to simply remove the offending type hint.

This was not an option for us, but we were able to work around the problem by using `typing.ForwwardRef`:

```python
CircularObj = typing.ForwardRef('CircularObj')
class CircularObj:
    circular:CircularObj
typing.get_type_hints(CircularObj)
```

both the `ForwardRef` before class definition and the call to `get_type_hints` after class definition are required.

this avoids the need for `localns=` hackery, and provides for a workaround without burdening library authors.

**Comment by Dacid99** [comment] 2025-03-02 17:10
I have the same issue as described above, the imports guarded by TYPE_CHECKING are not available to drf_spectacular.

I fixed this by removing the guard in the relevant places but would like to see a better solution.

Is there any way you can set TYPE_CHECKING to True when getting the schema for the api? 
Or maybe you could provide your own flag so one can guard the imports at runtime with 
if TYPE_CHECKING or SPECTACULAR_RUNNING ..

Thanks for the great project and for looking into this!

**Comment by tfranzel** [comment] 2025-03-02 19:12
@Dacid99, not sure whether there is a practical solution to this.

Not sure if we even **can** enable `TYPE_CHECKING`. It would **not** be advisable in any case. By definition, it is not meant to be executed at runtime. Turning this on might create unpredictable issues in many codebases. Also import order plays a role here. If you request a schema from the `SpectacularApiView`, you are inside the webserver. If stuff if loaded before setting this flag, the import would not happen, and the modules would be cached after that, creating race condition issues. Using `manage.py spectacular` would be more predictable, but would also create a potential discrepancy between running in the CLI and the webserver. 

Doing a `SPECTACULAR_RUNNING` has the same problems as above, just slightly less dangerous.

I believe adding some unpredictable hack here would create more problems than it solves. 

I believe I have not used `typing.ForwardRef` before, but it looks like best option here. @wilson0x4d, if there is some corner case initialziation issue, we might fix this in our type hint retrieval code. It possible that we simply are not paying attention to `ForwardRef` yet, which we could change. We do use `typing.get_type_hints` internally anyway.

**Comment by Dacid99** [comment] 2025-03-03 08:03
Alright that makes sense, Ill look into ForwardRef as a better fix.

Thanks for the quick response!
