### ISSUE TITLE
Request: minLength if allow_blank=False

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#282] opened 2021-02-01 13:09 UTC
Currently drf-yasg (from which were migrating)  adds `minLength: 1` to schema if field is not `required` and has `default` value, ie

```py
depth = serializers.CharField(required=False, default='2')
```
and this generates schema
```yaml
- name: depth
  in: query
  required: false
  type: string
  default: '2'
  minLength: 1
```

which means user CAN NOT make request `api.foo.com?depth=''`

drf-spectacular does not add `minLength` value for this
```yaml
- in: query
  name: depth
  schema:
    type: string
    default: '2'
```

This `minLength: 1` value should come from `allow_blank` attr that for `CharField` default to `False`

**Comment by johnthagen** [comment] 2021-10-13 20:16
This also seems related to or duplicate of #186

**Comment by tfranzel** [comment] 2021-10-15 22:19
had another detailed look. i was briefly misled by the `default`. imho it plays no relevant part here. `''` is a valid string and the default only comes into play when the field is actually missing.
 
extended `OpenApiParameter` to also expose this. I assume you used the exploded serializer for the parameters. this shortcut now makes use of `allow_blank==False`  and so your example should now work as expected.

**Comment by tfranzel** [comment] 2021-11-10 16:36
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-11-10 16:36 UTC
Labels: enhancement, fix confirmation pending

**Comment by johnthagen** [comment] 2021-11-10 16:37
@tfranzel I noticed that these checks were in the 0.21.0 schema as well.
