### ISSUE TITLE
AttributeError: module 'drf_spectacular.apps' has no attribute 'SpectacularSidecarConfig'

### ISSUE THREAD

**Issue by ygsh0816** [tfranzel/drf-spectacular#594] opened 2021-11-02 01:41 UTC
Traceback (most recent call last):

  File "/usr/local/bin/celery", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.7/site-packages/celery/__main__.py", line 16, in main

    _main()

  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main

    cmd.execute_from_commandline(argv)

  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline

    super(CeleryCommand, self).execute_from_commandline(argv)))

  File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline

    return self.handle_argv(self.prog_name, argv[1:])

  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 487, in handle_argv

    return self.execute(command, argv)

  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 419, in execute

    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])

  File "/usr/local/lib/python3.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv

    return self(*args, **options)

  File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 253, in __call__

    ret = self.run(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/bin/worker.py", line 258, in run

    **kwargs)

  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 99, in __init__

    self.app.loader.init_worker()

  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 114, in init_worker

    self.import_default_modules()

  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules

    raise response

  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send

    response = receiver(signal=self, sender=sender, **named)

  File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 84, in on_import_modules

    self.worker_fixup.validate_models()

  File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 122, in validate_models

    self.django_setup()

  File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 118, in django_setup

    django.setup()

  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate

    app_config = AppConfig.create(entry)

  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 118, in create

    cls = getattr(mod, cls_name)

AttributeError: module 'drf_spectacular.apps' has no attribute 'SpectacularSidecarConfig'

**Comment by tfranzel** [comment] 2021-11-02 10:36
Actually a dupe of #575, but finally saw the forest for the trees. 

This was a type in typo/bug in the sidecar though. (https://github.com/tfranzel/drf-spectacular-sidecar/commit/6741acff838672a77d29af6f1de320b6ab87bac8)

Please update to `drf-spectacular-sidecar==2021.11.2` and the problem should disappear.

**Comment by tfranzel** [comment] 2021-11-07 19:15
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Closed by tfranzel** 2021-11-07 19:15 UTC
Labels: bug, fix confirmation pending
